---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
        app: frontend
        service: frontend
spec:
    ports:
    - port: 3000
      name: http
    selector:
      app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend 
    labels:
        app: frontend
spec:
    selector:
        matchLabels:
            app: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: vue:1.0
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: backend
    labels:
        app: backend
        service: backend
spec:
    ports:
    - port: 3000
      name: http
    selector:
      app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    labels:
        app: backend
spec:
    selector:
        matchLabels:
            app: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: express:1.0
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 3000